---
- name: Copy index test page
  template:
    src: "~/project/artifact.tar.gz"
    dest: "~/"


- name: Executing node
  shell: |
    tar -xzvf artifact.tar.gz
    cd backend 
    npm install
    pm2 stop default
    pm2 start npm --start